name: reorderable_staggered_grid_view
description: A Flutter package for creating reorderable and staggered grid views.
version: 0.0.1+1

homepage: https://github.com/socrat-mniirs/reorderable_staggered_grid_view
repository: https://github.com/socrat-mniirs/reorderable_staggered_grid_view
issue_tracker: https://github.com/socrat-mniirs/reorderable_staggered_grid_view/issues

topics:
  - flutter
  - reorderable
  - grid
  - staggered
  - drag-and-drop

license: MIT

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  staggered_grid_view: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter: